import Head from "next/head";
import { useState } from "react";
import Lottie from "react-lottie";
import animationData from "../data/85819-kadokado-heart.json";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isStopped, setIsStopped] = useState(true);
  // const defaultOptions = {
  //   loop: true,
  //   autoplay: true,
  //   animationData: animationData,
  //   rendererSettings: {
  //     preserveAspectRatio: "xMidYMid slice",
  //   },
  // };

  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Lottie options={defaultOptions} height={200} width={200} /> */}
        <Lottie
          options={defaultOptions}
          height={200}
          width={200}
          isStopped={isStopped}
          eventListeners={[
            {
              eventName: "complete",
              callback: () => {
                setIsStopped(true);
                console.log("HERE");
              },
            },
          ]}
        />
        <button onClick={() => setIsStopped(false)}>Run animation</button>
      </main>
    </div>
  );
}
